version: '3'

services:
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    volumes:
      - serp_db_data:/var/lib/postgresql/data
    env_file: .env
    
  backend:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    env_file: .env
    
  redis:
    image: redis:5.0.5
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - serp_redis_data:/data
      
  celery:
    build: .
    command: ["celery", "-A", "serp", "worker", "-l", "info"]
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file: .env
    
volumes:
  serp_db_data:
    external: true
  serp_redis_data:
