# Generated by Django 2.2.3 on 2019-07-07 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_time_limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('default_user_agent', models.TextField()),
                ('proxies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('user_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('no_returned_results', models.IntegerField()),
                ('user_agent', models.TextField()),
                ('top_ten_words_headers', models.TextField()),
                ('top_ten_words_descriptions', models.TextField()),
                ('top_ten_words_both', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='serp_app.Search')),
            ],
        ),
    ]
