# Generated by Django 2.2.3 on 2019-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='example', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
