# Generated by Django 2.2.3 on 2019-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0002_auto_20190707_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.AlterField(
            model_name='search',
            name='top_ten_words_both',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='top_ten_words_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='top_ten_words_headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
