# Generated by Django 2.2.3 on 2019-07-07 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0003_auto_20190707_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('country', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='config',
            name='proxies',
        ),
        migrations.AddField(
            model_name='search',
            name='proxy_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
