# Generated by Django 2.2.3 on 2019-07-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0004_auto_20190707_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='no_returned_results',
            field=models.BigIntegerField(),
        ),
    ]
