# Generated by Django 2.2.3 on 2019-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serp_app', '0006_auto_20190708_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='task_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
